# This workflow tests if building a flatpak bundle from the manifest works.

name: build-flatpak

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      # Runs flatpak builder to test if building works
      - name: Flatpak Builder
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          # The relative path of the manifest file.
          manifest-path: eu.betterbird.Betterbird.json
          bundle: eu.betterbird.Betterbird.flatpak
